/**
 * Create a new rcm_payerdeckissue (HPI / Health Plan Issue) row.
 *
 * Schema-accurate write (verified against PROD 2026-07-10):
 *   - rcm_issuenumber is auto-generated by Dataverse (AutoNumberFormat
 *     "M-{SEQNUM:1}"). Never sent on create; the platform assigns it
 *     atomically. UI shows a live "next: M-XXX" preview computed from
 *     the cached HPI list purely for user awareness.
 *   - rcm_analyst is a lookup to systemuser. Written via
 *     rcm_Analyst@odata.bind and rendered as a team-scoped
 *     SearchableSelect (Payer Initiatives AAD team members only).
 *   - rcm_reservebucketpayer stays a free-text input per operator ask.
 */
import { useMemo, useState } from 'react';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '../../../../components/ui/dialog';
import { Input } from '../../../../components/ui/input';
import { Button } from '../../../../components/ui/button';
import { SearchableSelect } from '../../../../components/common/SearchableSelect';
import { toast } from '../../../../hooks/useToast';
import { useCreateHpiIssue, useHpiIssues, useRelateProjectToHpi } from '../hooks/useHpiIssues';
import { HpiRelateProjectPicker } from './HpiRelateProjectPicker';
import { AR_RECOVERY_TYPE_OPTIONS, RISK_OPTIONS, type ArRecoveryTypeValue, type RiskValue } from '../api/hpi.api';
import {
  resolveAnalystLabel,
  useActivePayerInitiativesAnalysts,
} from '../hooks/usePayerInitiativesAnalysts';

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated?: (newId: string) => void;
}


/** Peek at the current cached list to preview the next Dataverse-assigned
 *  M-XXX. Purely informational -- Dataverse is the source of truth. */
function useNextIssueNumberPreview(): string {
  const { data } = useHpiIssues();
  return useMemo(() => {
    if (!data || data.length === 0) return 'M-1';
    let max = 0;
    for (const row of data) {
      const m = /^M-(\d+)$/.exec(row.rcm_issuenumber ?? '');
      if (m) {
        const n = parseInt(m[1], 10);
        if (n > max) max = n;
      }
    }
    return `M-${max + 1}`;
  }, [data]);
}

export function HpiCreateDialog({ open, onOpenChange, onCreated }: Props) {
  const create = useCreateHpiIssue();
  const relate = useRelateProjectToHpi();
  const nextPreview = useNextIssueNumberPreview();
  const { data: analystOptions = [], isLoading: analystsLoading } = useActivePayerInitiativesAnalysts();

  const [name, setName] = useState('');
  const [analystId, setAnalystId] = useState('');
  const [payer, setPayer] = useState('');
  const [risk, setRisk] = useState<RiskValue | ''>('');
  const [credentialing, setCredentialing] = useState<boolean | undefined>(undefined);
  const [pathForward, setPathForward] = useState<boolean | undefined>(undefined);
  const [arType, setArType] = useState<ArRecoveryTypeValue | ''>('');
  const [projectIdToAttach, setProjectIdToAttach] = useState('');

  function reset() {
    setName(''); setAnalystId(''); setPayer('');
    setRisk(''); setCredentialing(undefined);
    setPathForward(undefined); setArType(''); setProjectIdToAttach('');
  }

  async function handleSave() {
    if (!name.trim()) {
      toast.error('Name is required.');
      return;
    }
    try {
      const row = await create.mutateAsync({
        // "Name" is stored in rcm_statusdetails (the RCM autonumber flow
        // clobbers rcm_name with the M- issue number).
        rcm_statusdetails: name.trim(),
        analystSystemUserId: analystId || undefined,
        rcm_reservebucketpayer: payer.trim() || undefined,
        rcm_risk: risk === '' ? undefined : risk,
        cr87a_credentialing: credentialing,
        cr87a_pathforward: pathForward,
        cr87a_arrecoverytype: arType === '' ? undefined : arType,
      });
      toast.success(`HPI ${row.rcm_issuenumber ?? ''} created.`);
      if (projectIdToAttach) {
        try {
          await relate.mutateAsync({ hpiId: row.rcm_payerdeckissueid, projectId: projectIdToAttach });
          toast.success('Project attached to HPI.');
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          toast.error(`HPI created, but attach failed: ${msg}`);
        }
      }
      onCreated?.(row.rcm_payerdeckissueid);
      reset();
      onOpenChange(false);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      toast.error(`Couldn’t create HPI: ${msg}`);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v && !create.isPending) onOpenChange(false); }}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>New HPI Issue Number</DialogTitle>
          <DialogDescription>
            Create a Health Plan Issue. Projects relate to this issue via the
            HPI field on the project form and the relate picker in the gallery.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-3 pt-2">
          <Field label="Issue Number">
            <Input
              value={`Auto-generated (next: ${nextPreview})`}
              disabled
              readOnly
              className="text-muted-foreground italic"
            />
            <p className="text-[10px] text-muted-foreground">
              Assigned automatically by Dataverse on save. Preview is a best-guess from the current cache; the platform is the source of truth.
            </p>
          </Field>
          <Field label="Name *">
            <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Describe the issue" />
          </Field>
          <div className="grid grid-cols-2 gap-3">
            <Field label="Analyst">
              <SearchableSelect
                value={analystId}
                onChange={setAnalystId}
                options={analystOptions}
                resolveLabel={resolveAnalystLabel}
                placeholder={analystsLoading ? "Loading team…" : "Select an analyst…"}
                disabled={analystsLoading}
              />
            </Field>
            <Field label="Reserve Bucket / Payer">
              <Input value={payer} onChange={(e) => setPayer(e.target.value)} />
            </Field>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <Field label="Risk">
              <select
                className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
                value={risk === '' ? '' : String(risk)}
                onChange={(e) => setRisk(e.target.value === '' ? '' : (Number(e.target.value) as RiskValue))}
              >
                <option value="">—</option>
                {RISK_OPTIONS.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            </Field>
            <Field label="Credentialing">
              <YesNoSelect value={credentialing} onChange={setCredentialing} />
            </Field>
            <Field label="Path Forward">
              <YesNoSelect value={pathForward} onChange={setPathForward} />
            </Field>
          </div>
          <Field label="AR Recovery Type">
            <select
              className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
              value={arType === '' ? '' : String(arType)}
              onChange={(e) => setArType(e.target.value === '' ? '' : (Number(e.target.value) as ArRecoveryTypeValue))}
            >
              <option value="">—</option>
              {AR_RECOVERY_TYPE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </Field>
          <Field label="Attach a Payer Initiatives project (optional)">
            <HpiRelateProjectPicker
              value={projectIdToAttach}
              onChange={setProjectIdToAttach}
              placeholder="Select a project…"
            />
            <p className="text-[10px] text-muted-foreground">Dropdown lists every active project owned by the Payer Initiatives team. Attaches via pmo_PayerInitiatives_HpiIssue on save. Leave blank to skip.</p>
          </Field>
        </div>
        <DialogFooter className="pt-3">
          <Button variant="secondary" size="sm" onClick={() => onOpenChange(false)} disabled={create.isPending}>
            Cancel
          </Button>
          <Button size="sm" onClick={handleSave} disabled={create.isPending || !name.trim()}>
            {create.isPending ? 'Saving…' : 'Create'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1">
      <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">{label}</p>
      {children}
    </div>
  );
}

function YesNoSelect({ value, onChange }: { value: boolean | undefined; onChange: (v: boolean | undefined) => void }) {
  const str = value === undefined ? '' : value ? 'true' : 'false';
  return (
    <select
      className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm"
      value={str}
      onChange={(e) => {
        const v = e.target.value;
        onChange(v === '' ? undefined : v === 'true');
      }}
    >
      <option value="">—</option>
      <option value="true">Yes</option>
      <option value="false">No</option>
    </select>
  );
}
